apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: hello-app
  name: hello-app
spec:
  replicas: 2
  selector:
    matchLabels:
      run: hello-app
  template:
    metadata:
      labels:
        run: hello-app
    spec:
      containers:
      - image: gcr.io/<google-project-id>/hello-app:latest
        name: hello-app
        ports:
        - containerPort: 80
